#!/bin/sh
# postinst script for renaconf
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

# create soft link
D='/usr/lib/pymodules/python2.7/renaconf'
S='/usr/share/pyshared/renaconf'

# list of files
files=("build_HAL.py" "build_INI.py" "pages.py" "import_mach.py")

# remove existing softlink
if [ -d ${D} ]; then
	for i in "${files[@]}"
	do
		rm -f ${D}/${i}
	done
	rm -f ${D}/__init__.py
else
	mkdir -p ${D}
fi

# create special file
touch ${D}/__init__.py

# create softlink
for i in "${files[@]}"
do
	ln -s ${S}/${i} ${D}/${i}
done

exit 0
