Document: renaconf
Title: Debian renaconf Manual
Author: <insert document author here>
Abstract: This manual describes what renaconf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/renaconf/renaconf.sgml.gz

Format: postscript
Files: /usr/share/doc/renaconf/renaconf.ps.gz

Format: text
Files: /usr/share/doc/renaconf/renaconf.text.gz

Format: HTML
Index: /usr/share/doc/renaconf/html/index.html
Files: /usr/share/doc/renaconf/html/*.html
